### ISSUE TITLE
run.sh 실행중 오류

### ISSUE THREAD

**Issue by ChoKyuWon** [18-2-SKKU-OSS/2018-2-OSS-L4#3]
run.sh 실행중에 다음과 같은 오류가 나는 현상

>[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/mnt/c/Users/조규원/Desktop/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/mnt/c/Users/조규원/Desktop/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/mnt/c/Users/조규원/Desktop/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/mnt/c/Users/조규원/Desktop/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
>
>During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 388, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 83, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
  File "run.py", line 36, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.
>
>[INFO] launcher: All done.

**Comment by ChoKyuWon** [comment]
python 3 버전의 pip을 사용해야 하네요
python 2 버전의 pip만 깔려있으면 위와 같은 오류가 발생합니다.
